## Практична робота 1, Варіант 6 (Чернігів)

**Прізвище та ім'я:** Войтович Богдан  
**Група:** IT-32


In [6]:
import numpy as np

temps = np.array([-5, -4, 1, 9, 15, 18, 20, 19, 13, 7, 1, -3])
days_in_month = np.array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])
month_numbers = np.arange(1, 13)

print("temps shape:", temps.shape, "dtype:", temps.dtype)
print("days_in_month shape:", days_in_month.shape, "dtype:", days_in_month.dtype)
print("month_numbers shape:", month_numbers.shape, "dtype:", month_numbers.dtype)


temps shape: (12,) dtype: int64
days_in_month shape: (12,) dtype: int64
month_numbers shape: (12,) dtype: int64


In [7]:
temps


array([-5, -4,  1,  9, 15, 18, 20, 19, 13,  7,  1, -3])

In [9]:
days_in_month

array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])

In [8]:
month_numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
print("temps shape:", temps.shape, "dtype:", temps.dtype)
print("days_in_month shape:", days_in_month.shape, "dtype:", days_in_month.dtype)
print("month_numbers shape:", month_numbers.shape, "dtype:", month_numbers.dtype)


temps shape: (12,) dtype: int64
days_in_month shape: (12,) dtype: int64
month_numbers shape: (12,) dtype: int64


In [11]:
temps_f = temps * 9 / 5 + 32
warm_months = temps > 15
days_warm = days_in_month[warm_months].sum()

print("Temps in Fahrenheit:", temps_f)
print("Days warmer than 15°C:", days_warm)
print("Days in year:", days_in_month.sum())


Temps in Fahrenheit: [23.  24.8 33.8 48.2 59.  64.4 68.  66.2 55.4 44.6 33.8 26.6]
Days warmer than 15°C: 92
Days in year: 365


In [12]:
max_temp = temps.max()
max_idx = temps.argmax()
min_temp = temps.min()
min_idx = temps.argmin()
cold_months = month_numbers[temps < 0]
sorted_temps = np.sort(temps)

print(f"Hottest month: {month_numbers[max_idx]} with {max_temp}°C")
print(f"Coldest month: {month_numbers[min_idx]} with {min_temp}°C")
print("Months with temperatures below 0°C:", cold_months)
print("Sorted temperatures:", sorted_temps)


Hottest month: 7 with 20°C
Coldest month: 1 with -5°C
Months with temperatures below 0°C: [ 1  2 12]
Sorted temperatures: [-5 -4 -3  1  1  7  9 13 15 18 19 20]


In [14]:
sun_hours = np.array([45, 50, 90, 140, 190, 210, 230, 220, 170, 110, 60, 40])
data = np.array([temps, days_in_month, sun_hours])

row_sums = data.sum(axis=1)
row_means = data.mean(axis=1)
col_sums = data.sum(axis=0)

print("Row sums:", row_sums)
print("Row means:", row_means)
print("Column sums:", col_sums)
print("Sum for January (first column):", col_sums[0])
print("This is the sum of temperature, days in January, and sun hours.")


Row sums: [  91  365 1555]
Row means: [  7.58333333  30.41666667 129.58333333]
Column sums: [ 71  74 122 179 236 258 281 270 213 148  91  68]
Sum for January (first column): 71
This is the sum of temperature, days in January, and sun hours.


In [15]:
rows = np.array([temps, days_in_month])
correction = np.array([1, 0])

print("rows shape:", rows.shape)
print("correction shape:", correction.shape)

try:
    result = rows + correction
except ValueError as e:
    print("Error:", e)

correction_reshaped = correction.reshape(2, 1)
result = rows + correction_reshaped
print("Result after reshape and addition:\n", result)


rows shape: (2, 12)
correction shape: (2,)
Error: operands could not be broadcast together with shapes (2,12) (2,) 
Result after reshape and addition:
 [[-4 -3  2 10 16 19 21 20 14  8  2 -2]
 [31 28 31 30 31 30 31 31 30 31 30 31]]
